version: "3.5"

services:
   rdf4j:
      container_name: opensilex-rdf4j
      image: eclipse/rdf4j-workbench:amd64-3.0.0-testing
      networks:
         - backend
      ports:
         - "8080:8080"
      restart: always         
      volumes:
         - rdf4j_data:/var/rdf4j
      environment:
         - JAVA_OPTS='-Dorg.eclipse.rdf4j.appdata.basedir=/var/rdf4j/'
         
   mongodb:
      container_name: opensilex-mongodb
      image: 'mongo:4.2.0-bionic'
      networks:
         - backend
      ports:
         - "27017:27017"
      restart: always         
      volumes:
         - mongodb_data:/data/db
         
   psql:
      container_name: opensilex-psql
      image: 'mdillon/postgis:9.5-alpine'
      networks:
         - backend
      ports:
         - "5432:5432"
      restart: always
      environment:
        POSTGRES_USER: opensilex
        POSTGRES_PASSWORD: opensilex
      volumes:
         - psql_data:/var/lib/postgresql/data

   pgadmin4:
      container_name: pgadmin4
      image: 'dpage/pgadmin4'
      networks:
         - backend
      ports:
         - "5433:80"
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@opensilex.org
        PGADMIN_DEFAULT_PASSWORD: opensilex      
    
networks:
   backend:

volumes:
   mongodb_data:
   rdf4j_data:
   psql_data:
