version: "3.5"

services:
   rdf4j:
      container_name: opensilex-rdf4j
      image: eclipse/rdf4j-workbench:amd64-3.0.0-testing
      networks:
         - backend
      ports:
         - "9000:8080"
      volumes:
         - rdf4j_data:/var/rdf4j
      environment:
         - JAVA_OPTS='-Dorg.eclipse.rdf4j.appdata.basedir=/var/rdf4j/'
         
   mongodb:
      container_name: opensilex-mongodb
      image: 'mongo:4.2.0-bionic'
      networks:
         - backend
      ports:
         - "9001:27017"
      volumes:
         - mongodb_data:/data/db
      
networks:
   backend:

volumes:
   mongodb_data:
   rdf4j_data:
