version: "3.5"

services:
   mongodb:
      container_name: mongodb
      image: 'bitnami/mongodb:latest'
      networks:
         - backend
      environment:
        - MONGODB_REPLICA_SET_MODE=primary
        - MONGODB_REPLICA_SET_NAME=opensilex
      labels:
         kompose.service.type: nodeport
      ports:
         - "8662:27017"
      volumes:
         - mongodb_data:/bitnami

   rdf4j:
      container_name: rdf4j
      build: './rdf4j'
      networks:
         - backend
      ports:
         - "8661:8080"
      volumes:
         - rdf4j_data:/var/rdf4j
      environment:
         - JAVA_OPTS='-Dorg.eclipse.rdf4j.appdata.basedir=/var/rdf4j/'
      
networks:
   backend:

volumes:
   mongodb_data:
   rdf4j_data:
