opensilex:
    sparql:
        rdf4j:
            serverURI: http://localhost:8080/rdf4j-server/
            repository: diaphen
    
    bigData:
        mongodb:
            database: diaphen
    
phisws:
    ontologyBaseURI: http://www.phenome-fppn.fr/
    vocabulary: http://www.phenome-fppn.fr/vocabulary/2017#
    infrastructure: diaphen
    
    uploadFileServerIP: localhost
    uploadFileServerUsername: vincent
    uploadFileServerPassword: pic3.14
    uploadFileServerDirectory: /home/vincent/opensilex/docs
    
    layerFileServerDirectory: /var/www/html/layers
    layerFileServerAddress: http://localhost/layers
    
    uploadImageServerDirectory: /var/www/html/images
    imageFileServerDirectory: http://localhost/images
        
    postgreSQL:
        database: diaphen
        username: phis
        password: azerty