ontologies:
    baseURI: http://www.opensilex.org/
    baseURIAlias: dev
    sparql:
        rdf4j:
            serverURI: http://localhost:8667/rdf4j-server/
            repository: opensilex

file-system: 
    storageBasePath: /home/bonnefoj/Documents/opensilexFiles

big-data:   
    nosql:
        mongodb:
            host: localhost
            port: 8668
            database: opensilex

phisws:
    postgreSQL:
        host: localhost
        port: 8669
        database: opensilex
        username: opensilex
        password: opensilex
        
    ontologyBaseURI: http://www.opensilex.org/
    vocabulary: http://www.opensilex.org/vocabulary/oeso
    infrastructure: opensilex
    
#    uploadFileServerIP: localhost
    uploadFileServerUsername: bonnefoj
    uploadFileServerPassword: pic3.14
    
    layerFileServerDirectory: /var/www/html/layers
    layerFileServerAddress: http://localhost/layers
    
    uploadImageServerDirectory: /var/www/html/images
    imageFileServerDirectory: http://localhost/images
        