ontologies:
    baseURI: http://opensilex.dev/
    baseURIAlias: dev
    sparql:
        #        implementation: org.opensilex.sparql.rdf4j.RDF4JInMemoryServiceFactory
        config:
            serverURI: http://localhost:8667/rdf4j-server/
            repository: opensilex


file-system:
    fs:
        config:
            basePath: ../../opensilex-data
#            defaultFS:
#                implementation: org.opensilex.fs.local.LocalFileSystemConnection
#            connections:
#                irods:                    
#                    implementation: org.opensilex.fs.irods.IrodsFileSystemConnection
#                    config:
#                        basePath: /FranceGrillesZone/home/fg-phenome/PHIS                
#            customPath:
#                datafile/: irods

big-data:   
    mongodb:
        config:
            host: localhost
            port: 8668
            database: opensilex
#            timezone: Europe/Paris
    
phisws:
    infrastructure: opensilex
    
#core:
#    enableLogs: true
#server:
#    pathPrefix: /sunagri
