ontologies:
    baseURI: http://www.phenome-fppn.fr/
    baseURIAlias: dev
    sparql:
#        implementation: org.opensilex.sparql.rdf4j.RDF4JInMemoryServiceFactory
        rdf4j:
            serverURI: http://localhost:7200
            repository: test

file-system: 
    storageBasePath: ../../opensilex-data

big-data:   
    nosql:
        mongodb:
            host: localhost
            port: 8668
            database: opensilex

phisws:
    infrastructure: opensilex