system:
    ignoredModules:
        opensilex.service.PhisWsModule: opensilex-phis.jar
    
ontologies:
    baseURI: http://opensilex.dev/
    baseURIAlias: dev
    enableSHACL: true
    sparql:
        config:
            serverURI: http://localhost:8667/rdf4j-server/
            repository: opensilex

file-system: 
    fs:
        config:
            basePath: ../../opensilex-data
#            connections:
#                irod: 
#                    implementation: org.opensilex.fs.irod.IRODSConnection
#                    config:
#                        baseURI: http://example.com/
#            customPath:
#                images: irod
    
big-data:
    nosql:
        config:
            connection:
                config:
                    host: localhost
                    port: 8668
                    database: opensilex

front:
    theme: inrae-sixtine#sixtine
    homeComponent: inrae-sixtine-SixtineHomeComponent
    loginComponent: inrae-sixtine-SixtineLoginComponent
    footerComponent: inrae-sixtine-SixtineFooterComponent
    menuComponent: inrae-sixtine-SixtineMenuComponent
    headerComponent: inrae-sixtine-SixtineHeaderComponent
    menuExclusions:
        - factors
        - germplasm
        - radiometricTargets
        - vectors
        - actuators
        - sensors
        - equipments
        - scientificObjects
        - installations
        - data
        - dashboard
    