name: trigger gitlab job
on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST "https://forgemia.inra.fr/api/v4/projects/$PROJECT_ID/trigger/pipeline?token=$TOKEN&ref=master"
      env: # Or as an environment variable
       TOKEN: ${{ secrets.FORGEMIA_TOKEN }}
       PROJECT_ID: 403
