name: trigger gitlab job
on: push
jobs:
 update_gitlab_upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name:  curl
      run: |
        git clone --recurse-submodules https://oauth2:${{ secrets.FORGEMIA_PAT }}@forgemia.inra.fr/OpenSILEX/opensilex.git
        cd opensilex/
        git fetch origin
        git checkout upstream
        git pull https://github.com/OpenSILEX/opensilex.git master
        git push origin upstream
